### ISSUE TITLE
`exclude` and `include` options do not seem to work

### ISSUE THREAD

**Issue by cedx** [cedx/ngx-inline-resources#1]
When I try the Rollup plugin, I get this kind of error:

```
[01:57:44] Error: ENOENT: no such file or directory, open 'C:\repo\pms-isol\web\my-component-tpl.html'
    at error (C:\repo\pms-isol\node_modules\rollup\dist\rollup.js:181:12)
    at C:\repo\pms-isol\node_modules\rollup\dist\rollup.js:9460:6
    at <anonymous>
```

The `my-component-tpl.html` URL does not come from my project, [it comes from the documentation of an Angular source file](https://github.com/angular/angular/blob/master/packages/animations/src/animation_metadata.ts).

**Comment by cedx** [comment]
Fixed in version 0.3.1.
